// Package configstore keeps the plain OpenTelemetry Collector config files that
// the OpAMP Server offers to Agents in an external object store (typically S3)
// and keeps an in-memory cache of them in sync.
//
// The object store is the source of truth. The Server never invents a config on
// its own: every config change made through the admin UI is written to the store
// first and is only then handed to the Agents, and any change made directly in
// the store (by a CI pipeline, GitOps job or a human with the AWS CLI) is picked
// up by the periodic sync and pushed to the affected Agents.
//
// # Layout
//
// Config files are plain YAML documents, stored verbatim so that they can be
// read and edited with any tool:
//
//	<prefix>/instances/<instance-id>.yaml   config for a single Agent instance
//	<prefix>/services/<service-name>.yaml   config for all instances of a service
//	<prefix>/default.yaml                   fallback config for every other Agent
//
// An Agent gets the first config that exists, in the order listed above, so an
// instance level file overrides a service level file, which in turn overrides
// the default. Keys used by this package are always relative to the configured
// prefix.
package configstore

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log"
	"maps"
	"path"
	"slices"
	"sort"
	"strings"
	"sync"
	"time"
)

// Well known locations inside the store.
const (
	// InstancesDir holds per Agent instance configs, named after the instance id.
	InstancesDir = "instances"
	// ServicesDir holds per service configs, named after the service.name attribute.
	ServicesDir = "services"
	// DefaultKey is the config handed to Agents that have no more specific config.
	DefaultKey = "default.yaml"

	// DefaultExtension is used for keys generated by this package.
	DefaultExtension = ".yaml"
)

// ConfigExtensions are the object suffixes recognized as config files. Objects
// under the prefix that do not end with one of these are ignored, so the bucket
// can also hold documentation, checksums or other bookkeeping files.
var ConfigExtensions = []string{".yaml", ".yml"}

// DefaultSyncInterval is how often the store is polled for out-of-band changes.
const DefaultSyncInterval = 30 * time.Second

// ErrNotFound is returned by Backend.Get for a key that does not exist.
var ErrNotFound = errors.New("config not found")

// Config is a single plain config file held by the backend.
type Config struct {
	// Key of the config file, relative to the backend prefix.
	Key string
	// Body is the verbatim content of the config file.
	Body []byte
	// Version is an opaque, backend specific version (the S3 ETag) that changes
	// whenever the content changes. It is used to avoid re-downloading unchanged
	// objects on every sync.
	Version string
	// ModifiedAt is when the config file was last written.
	ModifiedAt time.Time
}

// ObjectInfo is the metadata of a config file, as returned by a listing.
type ObjectInfo struct {
	Key        string
	Version    string
	ModifiedAt time.Time
}

// Backend is the storage that holds the config files. It is deliberately small
// so that S3, an S3 compatible store (MinIO, LocalStack) or an in-memory fake
// can all be plugged into the same Store.
type Backend interface {
	// List returns the metadata of every config file in the backend.
	List(ctx context.Context) ([]ObjectInfo, error)
	// Get returns the config file stored under key, or ErrNotFound.
	Get(ctx context.Context, key string) (Config, error)
	// Put stores body under key and returns the stored config.
	Put(ctx context.Context, key string, body []byte) (Config, error)
	// Location is a human readable description of where configs live, such as
	// "s3://my-bucket/otel-configs".
	Location() string
}

// Options configures a Store.
type Options struct {
	// SyncInterval is how often the backend is polled for changes made outside
	// of this Server. Defaults to DefaultSyncInterval.
	SyncInterval time.Duration
	// Logger receives sync progress and errors. Defaults to the standard logger.
	Logger *log.Logger
}

// Store is a cached, periodically synchronized view of a Backend.
//
// Reads (Resolve) are served from the cache so that they never block an Agent's
// status update on a network round trip, while writes (Save) go straight to the
// backend and only update the cache once the backend accepted them.
type Store struct {
	backend      Backend
	syncInterval time.Duration
	logger       *log.Logger

	mux     sync.RWMutex
	configs map[string]Config
	// loaded is set after the first successful sync, so that the initial load is
	// not reported as a series of changes.
	loaded bool

	onChangeMux sync.Mutex
	onChange    []func()

	stopOnce sync.Once
	cancel   context.CancelFunc
	done     chan struct{}
}

// New creates a Store on top of backend. Call Start to load the configs and to
// begin watching the backend for changes.
func New(backend Backend, opts Options) *Store {
	if opts.SyncInterval <= 0 {
		opts.SyncInterval = DefaultSyncInterval
	}
	if opts.Logger == nil {
		opts.Logger = log.New(
			log.Default().Writer(),
			"[CONFIGSTORE] ",
			log.Default().Flags()|log.Lmsgprefix|log.Lmicroseconds,
		)
	}

	return &Store{
		backend:      backend,
		syncInterval: opts.SyncInterval,
		logger:       opts.Logger,
		configs:      map[string]Config{},
		done:         make(chan struct{}),
	}
}

// Start performs the initial synchronization and then keeps syncing in the
// background until Stop is called or ctx is cancelled. It fails if the initial
// synchronization fails, so that a misconfigured or unreachable backend is
// reported at startup instead of silently handing out empty configs.
func (s *Store) Start(ctx context.Context) error {
	if _, err := s.Sync(ctx); err != nil {
		return fmt.Errorf("initial sync from %s failed: %w", s.backend.Location(), err)
	}

	s.logger.Printf("Loaded %d config(s) from %s", len(s.Keys()), s.backend.Location())

	loopCtx, cancel := context.WithCancel(ctx)
	s.cancel = cancel

	go s.syncLoop(loopCtx)

	return nil
}

// Stop ends the background synchronization and waits for it to finish.
func (s *Store) Stop() {
	s.stopOnce.Do(func() {
		if s.cancel != nil {
			s.cancel()
			<-s.done
		} else {
			close(s.done)
		}
	})
}

func (s *Store) syncLoop(ctx context.Context) {
	defer close(s.done)

	ticker := time.NewTicker(s.syncInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			changed, err := s.Sync(ctx)
			if err != nil {
				// Keep serving the configs we already have. The next tick retries.
				s.logger.Printf("Sync from %s failed, keeping the last known configs: %v",
					s.backend.Location(), err)
				continue
			}
			if changed {
				s.notifyChanged()
			}
		}
	}
}

// OnChange registers fn to be called after a background sync picked up a change
// in the backend. fn is called from the sync goroutine, outside of the Store
// lock, so it is free to call back into the Store.
func (s *Store) OnChange(fn func()) {
	s.onChangeMux.Lock()
	defer s.onChangeMux.Unlock()
	s.onChange = append(s.onChange, fn)
}

func (s *Store) notifyChanged() {
	s.onChangeMux.Lock()
	watchers := slices.Clone(s.onChange)
	s.onChangeMux.Unlock()

	for _, fn := range watchers {
		fn()
	}
}

// Sync refreshes the cache from the backend and reports whether anything
// changed. Objects whose version is unchanged are not downloaded again.
func (s *Store) Sync(ctx context.Context) (bool, error) {
	infos, err := s.backend.List(ctx)
	if err != nil {
		return false, fmt.Errorf("listing configs: %w", err)
	}

	s.mux.RLock()
	cached := maps.Clone(s.configs)
	isInitialLoad := !s.loaded
	s.mux.RUnlock()

	next := make(map[string]Config, len(infos))
	changed := false

	for _, info := range infos {
		if prev, ok := cached[info.Key]; ok && prev.Version != "" && prev.Version == info.Version {
			// Unchanged since the last sync, reuse the cached body.
			next[info.Key] = prev
			continue
		}

		cfg, err := s.backend.Get(ctx, info.Key)
		if err != nil {
			if errors.Is(err, ErrNotFound) {
				// Deleted between the listing and the fetch. Treat it as deleted.
				continue
			}
			return false, fmt.Errorf("fetching config %q: %w", info.Key, err)
		}

		next[info.Key] = cfg

		if prev, ok := cached[info.Key]; !ok || !bytes.Equal(prev.Body, cfg.Body) {
			changed = true
			if !isInitialLoad {
				s.logger.Printf("Config %q changed in %s", info.Key, s.backend.Location())
			}
		}
	}

	for key := range cached {
		if _, ok := next[key]; !ok {
			changed = true
			s.logger.Printf("Config %q was removed from %s", key, s.backend.Location())
		}
	}

	s.mux.Lock()
	s.configs = next
	s.loaded = true
	s.mux.Unlock()

	return changed && !isInitialLoad, nil
}

// Resolve returns the config that applies to the given Agent, looking up the
// candidate keys from the most to the least specific one. found is false when
// the store holds no config for the Agent at all.
func (s *Store) Resolve(instanceID, serviceName string) (key string, body []byte, found bool) {
	s.mux.RLock()
	defer s.mux.RUnlock()

	for _, candidate := range CandidateKeys(instanceID, serviceName) {
		if cfg, ok := s.configs[candidate]; ok {
			return cfg.Key, bytes.Clone(cfg.Body), true
		}
	}

	return "", nil, false
}

// DefaultKeyFor returns the key a config should be written to when the Agent
// does not have one yet: its own, instance specific config file.
func (s *Store) DefaultKeyFor(instanceID, serviceName string) string {
	return CandidateKeys(instanceID, serviceName)[0]
}

// Save writes body to key in the backend and, once the backend accepted it,
// updates the cache. The write is what makes the change durable, everything
// else (the UI, the Agents) is derived from it.
func (s *Store) Save(ctx context.Context, key string, body []byte) error {
	if err := ValidateKey(key); err != nil {
		return err
	}

	cfg, err := s.backend.Put(ctx, key, body)
	if err != nil {
		return fmt.Errorf("storing config %q in %s: %w", key, s.backend.Location(), err)
	}

	s.mux.Lock()
	s.configs[cfg.Key] = cfg
	s.mux.Unlock()

	s.logger.Printf("Stored config %q in %s (%d bytes)", cfg.Key, s.backend.Location(), len(body))

	return nil
}

// Get returns a cached config by key.
func (s *Store) Get(key string) (Config, bool) {
	s.mux.RLock()
	defer s.mux.RUnlock()

	cfg, ok := s.configs[key]
	if !ok {
		return Config{}, false
	}
	cfg.Body = bytes.Clone(cfg.Body)

	return cfg, true
}

// Keys returns the sorted keys of all cached configs.
func (s *Store) Keys() []string {
	s.mux.RLock()
	defer s.mux.RUnlock()

	keys := make([]string, 0, len(s.configs))
	for key := range s.configs {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	return keys
}

// Location describes where the configs are stored, for display purposes.
func (s *Store) Location() string {
	return s.backend.Location()
}

// CandidateKeys returns the keys that may hold the config of the given Agent,
// from the most to the least specific one.
func CandidateKeys(instanceID, serviceName string) []string {
	keys := make([]string, 0, 3)

	if id := sanitizeSegment(instanceID); id != "" {
		keys = append(keys, path.Join(InstancesDir, id+DefaultExtension))
	}
	if svc := sanitizeSegment(serviceName); svc != "" {
		keys = append(keys, path.Join(ServicesDir, svc+DefaultExtension))
	}

	return append(keys, DefaultKey)
}

// ValidateKey checks that key is a safe, relative key of a config file. It is
// applied to every key that reaches the backend, including the ones typed into
// the admin UI, so that a config cannot be written outside of the prefix.
func ValidateKey(key string) error {
	switch {
	case key == "":
		return errors.New("config key must not be empty")
	case strings.HasPrefix(key, "/"):
		return fmt.Errorf("config key %q must be relative to the store prefix", key)
	case strings.HasSuffix(key, "/"):
		return fmt.Errorf("config key %q must name a file, not a folder", key)
	case strings.ContainsAny(key, "\\\n\r"):
		return fmt.Errorf("config key %q contains invalid characters", key)
	case hasParentSegment(key):
		return fmt.Errorf("config key %q must not escape the store prefix", key)
	case path.Clean(key) != key:
		return fmt.Errorf("config key %q must be a clean relative path", key)
	case !HasConfigExtension(key):
		return fmt.Errorf("config key %q must end with one of %s",
			key, strings.Join(ConfigExtensions, ", "))
	}

	return nil
}

// HasConfigExtension reports whether key names a config file.
func HasConfigExtension(key string) bool {
	for _, ext := range ConfigExtensions {
		if strings.HasSuffix(key, ext) {
			return true
		}
	}

	return false
}

// hasParentSegment reports whether the key walks up the hierarchy. path.Clean
// keeps leading ".." segments, so they have to be rejected explicitly.
func hasParentSegment(key string) bool {
	for _, segment := range strings.Split(key, "/") {
		if segment == ".." {
			return true
		}
	}

	return false
}

// sanitizeSegment turns an arbitrary attribute value, such as a service name,
// into a single safe key segment. It returns an empty string for values that
// cannot produce a meaningful segment.
func sanitizeSegment(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}

	var b strings.Builder
	b.Grow(len(s))
	hasAlphanumeric := false
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			hasAlphanumeric = true
			b.WriteRune(r)
		case r == '-', r == '_', r == '.':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}

	if !hasAlphanumeric {
		// Nothing identifying is left, e.g. ".." or "///". Such a value must not
		// become a key of its own.
		return ""
	}

	// Avoid keys that would name a hidden or relative path.
	return strings.Trim(b.String(), ".")
}
